# Generated by Django 2.2.12 on 2022-06-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0004_userprofile_verified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='first_name',
            new_name='org_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
