# Generated by Django 2.2.12 on 2022-07-06 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0007_auto_20220706_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verified',
        ),
    ]
