# Generated by Django 4.0.6 on 2022-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0008_remove_userprofile_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='votosNegativos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='news',
            name='votosPositivos',
            field=models.IntegerField(default=0),
        ),
    ]
