# Generated by Django 4.0.6 on 2022-07-15 09:26

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0009_news_votosnegativos_news_votospositivos'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='voters',
            field=jsonfield.fields.JSONField(blank=True, default=dict),
        ),
    ]
