# Generated by Django 4.0.6 on 2022-07-15 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0018_alter_news_voters'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='orgId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
