# Generated by Django 4.0.6 on 2022-07-15 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0020_remove_userprofile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orgId',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
