# Generated by Django 4.0.6 on 2022-07-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0022_alter_userprofile_orgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='voters',
            field=models.JSONField(blank=True),
        ),
    ]
