# Generated by Django 4.0.6 on 2022-07-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0023_alter_news_voters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='voters',
            field=models.JSONField(default='{}'),
        ),
    ]
