# Generated by Django 4.0.6 on 2022-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0026_alter_userprofile_reputation'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='legitima',
            field=models.BooleanField(default=True),
        ),
    ]
