# Generated by Django 4.0.6 on 2022-08-04 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0030_alter_userprofile_orgid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orgId',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
