# Generated by Django 4.0.6 on 2022-08-04 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0031_alter_userprofile_orgid'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='canPublish',
            field=models.BooleanField(default=True),
        ),
    ]
