# Generated by Django 4.0.6 on 2022-09-12 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FakeApp', '0034_alter_userprofile_reputation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='orgId',
            field=models.IntegerField(default=-1, unique=True),
        ),
    ]
